
version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=loan_service_dev
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '6500:5432'
volumes:
  postgres:
